[pytest]
# Instruct pytest to generate both JUnit XML test logs and standard Coverage XML files
addopts = --cov=stream_bot --cov-report=xml:coverage.xml --junitxml=junit.xml --cov-report=term-missing
